from graphql import GraphQLResolveInfo as GraphQLResolveInfo
from typing import Any

def get_list(obj: Any, info: GraphQLResolveInfo, *args): ...
def get_doc(obj: Any, info: GraphQLResolveInfo, *args): ...
def save_doc(*args): ...
def delete_doc(*args): ...
def get_meta(obj: Any, info: GraphQLResolveInfo, doctype: str): ...
