import frappe
from _typeshed import Incomplete
from frappe.core.doctype.docfield.docfield import DocField as DocField
from frappe.model.meta import Meta as Meta
from frappe_gql_adaptor import resolvers as resolvers
from graphql import GraphQLField, GraphQLObjectType, GraphQLSchema

DEFAULT_FIELDS: Incomplete
CHILD_TABLE_FIELDS: Incomplete
INT_FIELDTYPES: Incomplete
FLOAT_FIELDTYPES: Incomplete
STRING_FIELDTYPES: Incomplete
doctype_interface: Incomplete
link_interface: Incomplete

def get_graphql_schema() -> GraphQLSchema: ...
def build_schema(meta: Meta, schema: frappe._dict) -> frappe._dict: ...
def get_graphql_field(schema: frappe._dict, docfield: DocField) -> GraphQLField: ...
def get_shallow_type(schema: frappe._dict, field: DocField) -> frappe._dict: ...
def get_interface(docfield: DocField) -> GraphQLObjectType: ...
def get_link_name(docfield: DocField) -> str: ...
def get_queries(schema: frappe._dict) -> GraphQLObjectType: ...
def get_mutations(schema: frappe._dict) -> GraphQLObjectType: ...
def get_stonecrop_meta() -> GraphQLField: ...
def remove_whitespace(text: str) -> str: ...
